version: "3.8"
services:
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: .pipeline/local.Dockerfile
    volumes:
      - ./:/srv/service
    image: "securityapi:local"
    ports:
      - 6927:6927
    environment:
      HOST: host.docker.internal
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_PORT: 3308
      FEED_PATH: ./tmp/feed.v2.test.json.gz
      QUERY_LIMIT: 10
    entrypoint: "./init.sh"
    restart: always
    networks:
      - wmnet
  db:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_TCP_PORT: 3307
    ports:
      - 3308:3307
    networks:
      - wmnet

networks:
  wmnet:
    name: wikimedia_network
